"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestBaselineOfLobster,
	#superclass : #PackageManifest,
	#category : #'BaselineOfLobster-Manifest'
}

{ #category : #'code-critics' }
ManifestBaselineOfLobster class >> ruleRBUtilityMethodsRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#BaselineOfLobster)) #'2020-02-25T23:48:08.317519-03:00') )
]
